version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hacker_news_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hacker_news
      - JWT_SECRET_WORD=your_secret_key
    depends_on:
      - db
    networks:
      - hacker_news_network

  db:
    image: postgres:15
    container_name: hacker_news_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hacker_news
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hacker_news_network

volumes:
  postgres_data:

networks:
  hacker_news_network:
    driver: bridge



# services:
#   database:
#     image: postgres:latest
#     container_name: database
#     restart: unless-stopped
#     .env_file:
#       - .env
#     volumes:
#       -hacker_news_dev_data:/var/lib/postgresql/data
#     networks:
#       - hacker_news_dev_network
#     expose:
#       - "5432"
#     ports:
#       - "5432:5432"
  
# volumes:
#   hacker_news_dev_data: